ALTER TABLE users ADD CONSTRAINT fk_users_customer_id FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_customer_id FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE wallets ADD CONSTRAINT fk_wallets_customer_id FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE wallets ADD CONSTRAINT fk_wallets_currency_id FOREIGN KEY (currency_id) REFERENCES currencies(id);
ALTER TABLE transaction_requests ADD CONSTRAINT fk_transaction_requests_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_transaction_type_id FOREIGN KEY (transaction_type_id) REFERENCES transaction_types(id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_debit_wallet_id FOREIGN KEY (debit_wallet_id) REFERENCES wallets(id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_credit_wallet_id FOREIGN KEY (credit_wallet_id) REFERENCES wallets(id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_currency_id FOREIGN KEY (currency_id) REFERENCES currencies(id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_customer_id FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_agent_customer_id FOREIGN KEY (agent_customer_id) REFERENCES customers(id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_transaction_reference FOREIGN KEY (transaction_reference) REFERENCES transaction_requests(transaction_reference);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_original_transaction_reference FOREIGN KEY (original_transaction_reference) REFERENCES transaction_requests(transaction_reference);
ALTER TABLE billers ADD CONSTRAINT fk_billers_settlement_wallet_id FOREIGN KEY (settlement_wallet_id) REFERENCES wallets(id);
ALTER TABLE biller_products ADD CONSTRAINT fk_biller_products_biller_id FOREIGN KEY (biller_id) REFERENCES billers(id);
ALTER TABLE biller_products ADD CONSTRAINT fk_biller_products_currency_id FOREIGN KEY (currency_id) REFERENCES currencies(id);
ALTER TABLE biller_products ADD CONSTRAINT fk_biller_products_settlement_wallet_id FOREIGN KEY (settlement_wallet_id) REFERENCES wallets(id);
ALTER TABLE fees ADD CONSTRAINT fk_fees_transaction_type_id FOREIGN KEY (transaction_type_id) REFERENCES transaction_types(id);
ALTER TABLE fees ADD CONSTRAINT fk_fees_biller_product_id FOREIGN KEY (biller_product_id) REFERENCES biller_products(id);
ALTER TABLE fees ADD CONSTRAINT fk_fees_currency_id FOREIGN KEY (currency_id) REFERENCES currencies(id);
ALTER TABLE bill_payments ADD CONSTRAINT fk_bill_payments_biller_id FOREIGN KEY (biller_id) REFERENCES billers(id);
ALTER TABLE bill_payments ADD CONSTRAINT fk_bill_payments_biller_product_id FOREIGN KEY (biller_product_id) REFERENCES biller_products(id);
ALTER TABLE bill_payments ADD CONSTRAINT fk_bill_payments_transaction_reference FOREIGN KEY (transaction_reference) REFERENCES transaction_requests(transaction_reference);
ALTER TABLE remittances ADD CONSTRAINT fk_remittances_sender_customer_id FOREIGN KEY (sender_customer_id) REFERENCES customers(id);
ALTER TABLE remittances ADD CONSTRAINT fk_remittances_receiver_customer_id FOREIGN KEY (receiver_customer_id) REFERENCES customers(id);
ALTER TABLE remittances ADD CONSTRAINT fk_remittances_provider_biller_id FOREIGN KEY (provider_biller_id) REFERENCES billers(id);
ALTER TABLE remittances ADD CONSTRAINT fk_remittances_source_currency_id FOREIGN KEY (source_currency_id) REFERENCES currencies(id);
ALTER TABLE remittances ADD CONSTRAINT fk_remittances_destination_currency_id FOREIGN KEY (destination_currency_id) REFERENCES currencies(id);
ALTER TABLE remittances ADD CONSTRAINT fk_remittances_transaction_reference FOREIGN KEY (transaction_reference) REFERENCES transaction_requests(transaction_reference);
ALTER TABLE remittances ADD CONSTRAINT fk_remittances_payout_transaction_reference FOREIGN KEY (payout_transaction_reference) REFERENCES transaction_requests(transaction_reference);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_biller_id FOREIGN KEY (biller_id) REFERENCES billers(id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_transactions_ledger_biller_product_id FOREIGN KEY (biller_product_id) REFERENCES biller_products(id);
ALTER TABLE transaction_requests ADD CONSTRAINT fk_transaction_requests_original_transaction_reference FOREIGN KEY (original_transaction_reference) REFERENCES transaction_requests(transaction_reference);
ALTER TABLE wallets ADD CONSTRAINT uq_wallet_currency UNIQUE(id,currency_id);
ALTER TABLE transactions_ledger ADD CONSTRAINT fk_debit_currency FOREIGN KEY(debit_wallet_id,currency_id) REFERENCES wallets(id,currency_id), ADD CONSTRAINT fk_credit_currency FOREIGN KEY(credit_wallet_id,currency_id) REFERENCES wallets(id,currency_id);
ALTER TABLE currencies ADD CONSTRAINT ck_currency_precision CHECK(decimal_places BETWEEN 0 AND 4);
ALTER TABLE fees ADD CONSTRAINT ck_fee_nonnegative CHECK((fixed_amount IS NULL OR fixed_amount>=0) AND (percentage IS NULL OR percentage>=0) AND (minimum_fee IS NULL OR minimum_fee>=0) AND (maximum_fee IS NULL OR maximum_fee>=0)), ADD CONSTRAINT ck_fee_range CHECK(minimum_fee IS NULL OR maximum_fee IS NULL OR minimum_fee<=maximum_fee);
ALTER TABLE biller_products ADD CONSTRAINT ck_reward_nonnegative CHECK(agent_reward_value>=0);
CREATE TRIGGER ledger_no_update BEFORE UPDATE ON transactions_ledger FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Posted ledger entries are immutable';
CREATE TRIGGER ledger_no_delete BEFORE DELETE ON transactions_ledger FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Financial history cannot be deleted';
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_logs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Audit logs are immutable';
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_logs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Audit logs cannot be deleted';
